{% set version = "0.10.1" %}

package:
  name: anaconda-project
  version: {{ version }}

source:
  url: https://github.com/Anaconda-Platform/anaconda-project/archive/v{{ version }}.tar.gz
  sha256: 2e26f358bcfcd957a801980a1ab2cb71891214abf94e258330e205a2da0f50b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - anaconda-project = anaconda_project.cli:main

requirements:
  host:
    - pip
    - python >=2.7

  run:
    - anaconda-client
    - conda-pack
    - python >=2.7
    - requests
    - ruamel_yaml
    - tornado >=4.2
    - jinja2

test:
  imports:
    - anaconda_project
  commands:
    - echo "First of test commands"
    - anaconda-project --help
    - anaconda-project --version
    - echo "Last of test commands"

about:
  home: https://github.com/Anaconda-Platform/anaconda-project
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Tool for encapsulating, running, and reproducing data science projects
  description: |
    By adding an anaconda-project.yml to a project directory, a single 
    anaconda-project runcommand will be able to set up all dependencies 
    and then launch the project.
  doc_url: http://anaconda-project.readthedocs.io
  dev_url: https://github.com/Anaconda-Platform/anaconda-project

extra:
  recipe-maintainers:
    - fpliger
    - goanpeca
    - mingwandroid
    - bollwyvl
