travis:
  secure:
    BINSTAR_TOKEN: jK+VRTSlEUdk61vVyg3x/10LRRTZzGRlL7+Rfm5C2gbNQGXFzF4lnIW4Oc7jlXDe8uK10vARnsIv61AT0f87CCxy3QeLSEKsIZtduVhlXjthy6WQQuyACG9vJgkqcTCeHB53lInPGfEmIyAgQiu2iCmZOZBmWyWZBO/HOfnty0vQRqg3IXbqn5efWE5sJ1SUXcHF0yWh1kZXjLW7Knl9RAjoTsigyX7Vrxr7z1zDLcrf1nTzHOxuS5d71boHW8cSloeNFimolfilHih7F8NvCBMfkvofNShUUvj+J0R1re8Wi05pVh3KauBIp4L/W4+2+TxmtKjmWhI9o0l9t1vSgtCRoBCgTZMLMSRYPqGWRUik3vxEJwEVL1M/p66QmqC5bjF1HE3vrm4+dg+o/ZM85VWEwhFFVaG3ammYeaoF+DKjiW4F0ox0PyDxmADMS0spytouIJELi9NUXu7l/8lTiJVVj2YD+zst0F0LIEEDBWhGMW6DkoS0SxrAzMGVyk8jRbsE4l4TK/TACdYLL7P2b5N1NiIrm6RNGgV3jap3t5q8JsEg5zMPVcgsbqoxwPfsDp/mEM0wMo9jDk6pAKKaaGqTMwKE4Z1YEJ+t/wueO5SFX8LMkkX3DXZkS8d001FGgKieZZB3KSO/SexUCAdll5YDKNDkgdZg00ljVYfCDAw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
